name: Security Audit

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm install --ignore-scripts
      - run: npm audit --production
