create table if not exists public.marketing_lead_audit_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  event_type text not null check (event_type in ('accepted', 'rejected')),
  reason text not null,
  lead_name text,
  lead_email text,
  ip text,
  user_agent text,
  metadata jsonb
);

comment on table public.marketing_lead_audit_events is 'Audit trail for marketing lead submissions and validation outcomes.';
comment on column public.marketing_lead_audit_events.event_type is 'accepted or rejected outcome for the submission.';
comment on column public.marketing_lead_audit_events.reason is 'Primary reason describing the acceptance or rejection result.';

create index if not exists marketing_lead_audit_events_event_type_idx
  on public.marketing_lead_audit_events (event_type, created_at desc);

create index if not exists marketing_lead_audit_events_created_at_idx
  on public.marketing_lead_audit_events (created_at desc);

alter table public.marketing_lead_audit_events enable row level security;

revoke all on public.marketing_lead_audit_events from anon;
revoke all on public.marketing_lead_audit_events from authenticated;
