// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getTableSessionHeader } from '@/lib/table-session';

const SUPABASE_URL = "https://elhlcdiosomutugpneoc.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaGxjZGlvc29tdXR1Z3BuZW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDU3NTMsImV4cCI6MjA3NDQ4MTc1M30.d92ZJG5E_9r7bOlRLBXRI6gcB_7ERVbL-Elp7fk4avY";

if (!SUPABASE_URL) {
  throw new Error('VITE_SUPABASE_URL is not set. Please provide it in your environment configuration.');
}

if (!SUPABASE_ANON_KEY) {
  throw new Error('VITE_SUPABASE_ANON_KEY is not set. Please provide it in your environment configuration.');
}

const authStorage = typeof window !== 'undefined' ? window.localStorage : undefined;

const withTableSession: typeof fetch = (input, init = {}) => {
  const headers = new Headers(init?.headers ?? {});
  if (typeof window !== 'undefined') {
    const sessionId = getTableSessionHeader();
    if (sessionId) {
      headers.set('x-icupa-session', sessionId);
    }
  }
  return fetch(input, { ...init, headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: withTableSession,
  },
});
