name: Generate SBOM

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'agents-service/package.json'
      - 'agents-service/package-lock.json'

permissions:
  contents: write

jobs:
  sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.2'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '10'
        run_install: false
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install CycloneDX generator
      run: npm install -g @cyclonedx/cyclonedx-npm
    
    - name: Generate SBOM for root workspace
      continue-on-error: true
      run: |
        mkdir -p docs/sbom
        cyclonedx-npm --output-format JSON --output-file docs/sbom/icupa-root.json || echo "Root SBOM generation had warnings"
    
    - name: Generate SBOM for agents service
      continue-on-error: true
      run: |
        cd agents-service
        cyclonedx-npm --output-format JSON --output-file ../docs/sbom/agents-service.json || echo "Agents SBOM generation had warnings"
        cd ..
    
    - name: Generate SBOM summary
      run: |
        cat > docs/sbom/README.md << 'EOF'
        # Software Bill of Materials (SBOM)
        
        Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        Format: CycloneDX 1.4 (JSON)
        
        ## Files
        
        - `icupa-root.json` - Root workspace dependencies
        - `agents-service.json` - Agents service dependencies
        
        ## Validation
        
        To validate these SBOMs:
        
        ```bash
        npm install -g @cyclonedx/cyclonedx-cli
        cyclonedx-cli validate --input-file docs/sbom/icupa-root.json
        ```
        
        ## Usage
        
        These SBOMs can be used for:
        - Dependency tracking
        - Vulnerability scanning
        - License compliance
        - Supply chain security
        EOF
    
    - name: Commit SBOMs
      if: github.event_name == 'push'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/sbom/
        git diff --staged --quiet || git commit -m "chore: update SBOM [skip ci]"
        git push
    
    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sbom-${{ github.sha }}
        path: docs/sbom/
        retention-days: 90

    - name: Attach SBOMs to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          docs/sbom/icupa-root.json
          docs/sbom/agents-service.json
          docs/sbom/README.md
