name: Supabase Deploy Functions

on:
  workflow_dispatch:
    inputs:
      project_ref:
        description: Supabase project ref (xxxxxx)
        required: true
      verify_jwt:
        description: Use JWT verification on Edge Functions
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then echo "Missing SUPABASE_ACCESS_TOKEN secret" && exit 1; fi
          supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Deploy Edge Functions
        env:
          PROJECT_REF: ${{ inputs.project_ref }}
        run: |
          chmod +x scripts/supabase/deploy-functions.sh
          if [ "${{ inputs.verify_jwt }}" = "true" ]; then
            scripts/supabase/deploy-functions.sh --project "$PROJECT_REF" --verify-jwt
          else
            scripts/supabase/deploy-functions.sh --project "$PROJECT_REF"
          fi

  post-health:
    needs: deploy
    uses: ./.github/workflows/post-deploy-health.yml
    with:
      base_url: https://${{ inputs.project_ref }}.functions.supabase.co
